# Generated by Django 2.2.6 on 2019-10-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191018_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='finished',
        ),
    ]
